# Generated by Django 3.2.4 on 2021-10-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstate',
            name='price',
        ),
    ]
