# Generated by Django 3.2.4 on 2021-10-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_productstate_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstate',
            name='units',
        ),
    ]
