# Generated by Django 3.2.4 on 2021-10-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_productstate_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_title', models.CharField(max_length=200)),
                ('promo_details', models.CharField(max_length=400)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.distributor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productstate')),
            ],
        ),
    ]
