# Generated by Django 3.2.4 on 2021-10-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_promo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promo',
            new_name='Promotion',
        ),
    ]
