# Generated by Django 3.2.4 on 2021-10-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_promo_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='promo_details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='promo_title',
            new_name='title',
        ),
    ]
