# Generated by Django 3.2.4 on 2021-10-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_promotion_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='product',
            new_name='product_state',
        ),
    ]
