# Generated by Django 3.2.4 on 2021-10-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_product_promotion_product_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstate',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
