# Generated by Django 3.2.4 on 2021-10-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_productstate_is_promoted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='distributor',
        ),
    ]
