# Generated by Django 3.2.4 on 2021-10-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payement_mode',
            field=models.CharField(choices=[('CE', 'Check'), ('CA', 'Cash')], default='CA', max_length=2),
        ),
    ]
