# Generated by Django 3.2.4 on 2021-10-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_payement_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payement_mode',
        ),
    ]
