# Generated by Django 3.2.4 on 2021-10-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_order_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='purchase_price',
            field=models.FloatField(default=0.0),
        ),
    ]
