# Generated by Django 3.2.4 on 2022-01-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstate',
            name='category',
        ),
        migrations.AddField(
            model_name='productstate',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.family'),
        ),
    ]
