# Generated by Django 3.2.4 on 2022-01-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220112_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unit',
        ),
    ]
